--[[This file was generated by Void Private Dumper v1.4]]
local vScreenGui_380 = Instance.new("ScreenGui")
vScreenGui_380.Name = "CryHubLagger"
local CoreGui = game:GetService('CoreGui')
vScreenGui_380.Parent = CoreGui
vScreenGui_380.ZIndexBehavior = Enum.ZIndexBehavior.Sibling
vScreenGui_380.ResetOnSpawn = false
local vFrame_785 = Instance.new("Frame")
vFrame_785.Name = "MainFrame"
vFrame_785.Parent = vScreenGui_380
vFrame_785.BackgroundColor3 = Color3.fromRGB(22, 33, 62)
vFrame_785.BorderSizePixel = 0
vFrame_785.Position = UDim2.new(0.5, -100, 0.5, -75)
vFrame_785.Size = UDim2.new(0, 200, 0, 150)
vFrame_785.Active = true
vFrame_785.Draggable = true
local vUICorner_553 = Instance.new("UICorner")
vUICorner_553.CornerRadius = UDim.new(0, 8)
vUICorner_553.Parent = vFrame_785
local vUIGradient_357 = Instance.new("UIGradient")
vUIGradient_357.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, Color3.fromRGB(22, 33, 62)),
    ColorSequenceKeypoint.new(0.5, Color3.fromRGB(15, 22, 38)),
    ColorSequenceKeypoint.new(1, Color3.fromRGB(26, 26, 46))
})
vUIGradient_357.Rotation = 135
vUIGradient_357.Parent = vFrame_785
local vFrame_955 = Instance.new("Frame")
vFrame_955.Name = "TitleBar"
vFrame_955.Parent = vFrame_785
vFrame_955.BackgroundColor3 = Color3.fromRGB(30, 58, 95)
vFrame_955.BorderSizePixel = 0
vFrame_955.Size = UDim2.new(1, 0, 0, 25)
local vUICorner_631 = Instance.new("UICorner")
vUICorner_631.CornerRadius = UDim.new(0, 8)
vUICorner_631.Parent = vFrame_955
local vUIGradient_177 = Instance.new("UIGradient")
vUIGradient_177.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, Color3.fromRGB(30, 58, 95)),
    ColorSequenceKeypoint.new(1, Color3.fromRGB(13, 27, 42))
})
vUIGradient_177.Rotation = 135
vUIGradient_177.Parent = vFrame_955
local vTextLabel_374 = Instance.new("TextLabel")
vTextLabel_374.Name = "TitleLabel"
vTextLabel_374.Parent = vFrame_955
vTextLabel_374.BackgroundTransparency = 1
vTextLabel_374.Position = UDim2.new(0, 8, 0, 0)
vTextLabel_374.Size = UDim2.new(0.8, 0, 1, 0)
vTextLabel_374.Font = Font.GothamBold
vTextLabel_374.Text = "CryHub Lagger"
vTextLabel_374.TextColor3 = Color3.fromRGB(255, 255, 255)
vTextLabel_374.TextSize = 10
vTextLabel_374.TextXAlignment = Enum.TextXAlignment.Left
local vTextButton_132 = Instance.new("TextButton")
vTextButton_132.Name = "CloseButton"
vTextButton_132.Parent = vFrame_955
vTextButton_132.BackgroundColor3 = Color3.fromRGB(255, 68, 68)
vTextButton_132.BorderSizePixel = 0
vTextButton_132.Position = UDim2.new(1, -20, 0.5, -6)
vTextButton_132.Size = UDim2.new(0, 12, 0, 12)
vTextButton_132.Text = "✕"
vTextButton_132.TextColor3 = Color3.fromRGB(255, 255, 255)
vTextButton_132.TextSize = 8
vTextButton_132.Font = Font.GothamBold
vTextButton_132.AutoButtonColor = false
local vUICorner_743 = Instance.new("UICorner")
vUICorner_743.CornerRadius = UDim.new(1, 0)
vUICorner_743.Parent = vTextButton_132
local vTextLabel_951 = Instance.new("TextLabel")
vTextLabel_951.Name = "DiscordLabel"
vTextLabel_951.Parent = vFrame_785
vTextLabel_951.BackgroundTransparency = 1
vTextLabel_951.Position = UDim2.new(1, -80, 1, -15)
vTextLabel_951.Size = UDim2.new(0, 75, 0, 12)
vTextLabel_951.Font = Font.GothamBold
vTextLabel_951.Text = "discord.gg/cryhubb"
vTextLabel_951.TextColor3 = Color3.fromRGB(114, 137, 218)
vTextLabel_951.TextSize = 6
vTextLabel_951.TextXAlignment = Enum.TextXAlignment.Right
local vTextLabel_612 = Instance.new("TextLabel")
vTextLabel_612.Name = "ServerLabel"
vTextLabel_612.Parent = vFrame_785
vTextLabel_612.BackgroundTransparency = 1
vTextLabel_612.Position = UDim2.new(0, 8, 1, -15)
vTextLabel_612.Size = UDim2.new(0, 60, 0, 12)
vTextLabel_612.Font = Font.Gotham
vTextLabel_612.Text = "Discord: cryxn."
vTextLabel_612.TextColor3 = Color3.fromRGB(180, 180, 180)
vTextLabel_612.TextSize = 5
vTextLabel_612.TextXAlignment = Enum.TextXAlignment.Left
local vFrame_28 = Instance.new("Frame")
vFrame_28.Name = "ContentFrame"
vFrame_28.Parent = vFrame_785
vFrame_28.BackgroundTransparency = 1
vFrame_28.Position = UDim2.new(0, 5, 0, 30)
vFrame_28.Size = UDim2.new(1, -10, 1, -45)
local vTextButton_330 = Instance.new("TextButton")
vTextButton_330.Name = "StartButton"
vTextButton_330.Parent = vFrame_28
vTextButton_330.BackgroundColor3 = Color3.fromRGB(255, 68, 68)
vTextButton_330.BorderSizePixel = 0
vTextButton_330.Position = UDim2.new(0.5, -60, 0.1, 0)
vTextButton_330.Size = UDim2.new(0, 120, 0, 30)
vTextButton_330.Text = "START LAG"
vTextButton_330.Font = Font.GothamBold
vTextButton_330.TextSize = 12
vTextButton_330.TextColor3 = Color3.fromRGB(255, 255, 255)
vTextButton_330.AutoButtonColor = false
local vUICorner_56 = Instance.new("UICorner")
vUICorner_56.CornerRadius = UDim.new(0, 4)
vUICorner_56.Parent = vTextButton_330
local vUIGradient_639 = Instance.new("UIGradient")
vUIGradient_639.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, Color3.fromRGB(255, 68, 68)),
    ColorSequenceKeypoint.new(1, Color3.fromRGB(200, 30, 30))
})
vUIGradient_639.Rotation = 45
vUIGradient_639.Parent = vTextButton_330
local vTextLabel_132 = Instance.new("TextLabel")
vTextLabel_132.Name = "StatusLabel"
vTextLabel_132.Parent = vFrame_28
vTextLabel_132.BackgroundTransparency = 1
vTextLabel_132.Position = UDim2.new(0, 0, 0.5, 0)
vTextLabel_132.Size = UDim2.new(1, 0, 0, 16)
vTextLabel_132.Font = Font.GothamBold
vTextLabel_132.Text = "Bypassing Anticheat..."
vTextLabel_132.TextColor3 = Color3.fromRGB(255, 165, 0)
vTextLabel_132.TextSize = 10
vTextLabel_132.TextXAlignment = Enum.TextXAlignment.Center
vTextLabel_132.Visible = false
local vFrame_847 = Instance.new("Frame")
vFrame_847.Name = "LoadingBarBG"
vFrame_847.Parent = vFrame_28
vFrame_847.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
vFrame_847.BorderSizePixel = 0
vFrame_847.Position = UDim2.new(0.5, -80, 0.7, 0)
vFrame_847.Size = UDim2.new(0, 160, 0, 8)
vFrame_847.Visible = false
local vUICorner_864 = Instance.new("UICorner")
vUICorner_864.CornerRadius = UDim.new(0, 4)
vUICorner_864.Parent = vFrame_847
local vFrame_597 = Instance.new("Frame")
vFrame_597.Name = "LoadingBarFill"
vFrame_597.Parent = vFrame_847
vFrame_597.BackgroundColor3 = Color3.fromRGB(0, 255, 127)
vFrame_597.BorderSizePixel = 0
vFrame_597.Position = UDim2.new(0, 0, 0, 0)
vFrame_597.Size = UDim2.new(0, 0, 1, 0)
local vUICorner_721 = Instance.new("UICorner")
vUICorner_721.CornerRadius = UDim.new(0, 4)
vUICorner_721.Parent = vFrame_597
local vUIGradient_854 = Instance.new("UIGradient")
vUIGradient_854.Color = ColorSequence.new({
    ColorSequenceKeypoint.new(0, Color3.fromRGB(0, 255, 127)),
    ColorSequenceKeypoint.new(1, Color3.fromRGB(0, 200, 100))
})
vUIGradient_854.Rotation = 45
vUIGradient_854.Parent = vFrame_597
local vTextLabel_15 = Instance.new("TextLabel")
vTextLabel_15.Name = "LoadingPercent"
vTextLabel_15.Parent = vFrame_28
vTextLabel_15.BackgroundTransparency = 1
vTextLabel_15.Position = UDim2.new(0, 0, 0.85, 0)
vTextLabel_15.Size = UDim2.new(1, 0, 0, 14)
vTextLabel_15.Font = Font.Gotham
vTextLabel_15.Text = "0%"
vTextLabel_15.TextColor3 = Color3.fromRGB(180, 180, 180)
vTextLabel_15.TextSize = 9
vTextLabel_15.TextXAlignment = Enum.TextXAlignment.Center
vTextLabel_15.Visible = false
vTextButton_330.MouseButton1Click:Connect(function(arg1, arg2, arg3, arg4, arg5)
    vTextButton_330.Visible = false
    vTextLabel_132.Visible = true
    vFrame_847.Visible = true
    vTextLabel_15.Visible = true
    vTextLabel_132.Text = "Initializing..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 165, 0)
    vTextLabel_15.Text = "0%"
    local v_167 = vFrame_597:TweenSize(UDim2.new(0.0, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Bypassing Anticheat..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 165, 0)
    vTextLabel_15.Text = "5%"
    local v_172 = vFrame_597:TweenSize(UDim2.new(0.05, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Scanning Security..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 150, 0)
    vTextLabel_15.Text = "10%"
    local v_177 = vFrame_597:TweenSize(UDim2.new(0.1, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Cracking Protection..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 140, 0)
    vTextLabel_15.Text = "15%"
    local v_182 = vFrame_597:TweenSize(UDim2.new(0.15, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Disabling Detection..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 130, 0)
    vTextLabel_15.Text = "20%"
    local v_187 = vFrame_597:TweenSize(UDim2.new(0.2, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Hooking Functions..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 120, 0)
    vTextLabel_15.Text = "25%"
    local v_192 = vFrame_597:TweenSize(UDim2.new(0.25, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Injecting Payload..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 110, 0)
    vTextLabel_15.Text = "30%"
    local v_197 = vFrame_597:TweenSize(UDim2.new(0.3, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Loading Lag Scripts..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 100, 0)
    vTextLabel_15.Text = "35%"
    local v_202 = vFrame_597:TweenSize(UDim2.new(0.35, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Patching Memory..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 90, 0)
    vTextLabel_15.Text = "40%"
    local v_207 = vFrame_597:TweenSize(UDim2.new(0.4, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Bypassing Filters..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 80, 0)
    vTextLabel_15.Text = "45%"
    local v_212 = vFrame_597:TweenSize(UDim2.new(0.45, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Hooking Network..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 70, 0)
    vTextLabel_15.Text = "50%"
    local v_217 = vFrame_597:TweenSize(UDim2.new(0.5, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Modifying Packets..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 69, 0)
    vTextLabel_15.Text = "55%"
    local v_222 = vFrame_597:TweenSize(UDim2.new(0.55, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Injecting Delays..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 60, 0)
    vTextLabel_15.Text = "60%"
    local v_227 = vFrame_597:TweenSize(UDim2.new(0.6, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Creating Lag Spikes..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 50, 0)
    vTextLabel_15.Text = "65%"
    local v_232 = vFrame_597:TweenSize(UDim2.new(0.65, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Overloading Buffer..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 40, 0)
    vTextLabel_15.Text = "70%"
    local v_237 = vFrame_597:TweenSize(UDim2.new(0.7, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Activating Lag Switch..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 30, 0)
    vTextLabel_15.Text = "75%"
    local v_242 = vFrame_597:TweenSize(UDim2.new(0.75, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Finalizing Injection..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 20, 0)
    vTextLabel_15.Text = "80%"
    local v_247 = vFrame_597:TweenSize(UDim2.new(0.8, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Testing Lag System..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 10, 0)
    vTextLabel_15.Text = "85%"
    local v_252 = vFrame_597:TweenSize(UDim2.new(0.85, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Optimizing Performance..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(255, 0, 0)
    vTextLabel_15.Text = "90%"
    local v_257 = vFrame_597:TweenSize(UDim2.new(0.9, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Completing Setup..."
    vTextLabel_132.TextColor3 = Color3.fromRGB(200, 0, 0)
    vTextLabel_15.Text = "95%"
    local v_262 = vFrame_597:TweenSize(UDim2.new(0.95, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    vTextLabel_132.Text = "Lag Successfully Activated!"
    vTextLabel_132.TextColor3 = Color3.fromRGB(0, 255, 127)
    vTextLabel_15.Text = "100%"
    local v_267 = vFrame_597:TweenSize(UDim2.new(1.0, 0, 1, 0), "Out", "Quad", 0.4, true)
    task.wait(3)
    task.wait(1)
    vTextLabel_132.Text = "🔥 Lagging Enabled! 🔥"
    vTextLabel_132.TextColor3 = Color3.fromRGB(0, 255, 0)
    task.wait(3)
    vTextLabel_132.Visible = false
    vFrame_847.Visible = false
    vTextLabel_15.Visible = false
    vFrame_597.Size = UDim2.new(0, 0, 1, 0)
    vTextButton_330.Visible = true
    vTextButton_330.Text = "START LAG"
end)
vTextButton_330.MouseEnter:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_281 = vTextButton_330:TweenSize(UDim2.new(0, 125, 0, 32), "Out", "Quad", 0.2, true)
end)
vTextButton_330.MouseLeave:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_284 = vTextButton_330:TweenSize(UDim2.new(0, 120, 0, 30), "Out", "Quad", 0.2, true)
end)
vTextButton_132.MouseButton1Click:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_287 = vTextButton_132:TweenSize(UDim2.new(0, 10, 0, 10), "Out", "Quad", 0.1, true, function(arg1, arg2, arg3, arg4, arg5)
    local v_1 = vTextButton_132:TweenSize(UDim2.new(0, 12, 0, 12), "Out", "Quad", 0.1, true)
end)
    task.wait(0.2)
    local v_289 = vFrame_785:TweenSize(UDim2.new(0, 0, 0, 0), "Out", "Quad", 0.3, true)
    task.wait(0.3)
    local v291 = vScreenGui_380:Destroy()
end)
vTextButton_132.MouseEnter:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_294 = vTextButton_132:TweenSize(UDim2.new(0, 14, 0, 14), "Out", "Quad", 0.2, true)
end)
vTextButton_132.MouseLeave:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_297 = vTextButton_132:TweenSize(UDim2.new(0, 12, 0, 12), "Out", "Quad", 0.2, true)
end)
print("🔥 CryHub Lagger loaded!")
print("💥 Click 'START LAGGING' to begin 1-minute bypass!")
print("🎯 Type '.l' in chat to trigger client-side lag!")
local Players = game:GetService('Players')
local RunService = game:GetService('RunService')
local v304 = Players:GetPlayers()
Players.PlayerAdded:Connect(function(arg1, arg2, arg3, arg4, arg5)
    arg1.Chatted:Connect(function(arg1, arg2, arg3, arg4, arg5)
        local v_307 = arg1.lower()
        local v_308 = v_307.find("%.l")
        -- Concatenation: 🎯 Lag trigger detected from:  .. arg1.Name
        print("🎯 Lag trigger detected from: arg1.Name")
        print("🔥 EXTREME LAG TRIGGER ACTIVATED!")
    end)
end)
game.Players.LocalPlayer.Chatted:Connect(function(arg1, arg2, arg3, arg4, arg5)
    local v_315 = arg1.lower()
    local v_316 = v_315.find("%.l")
    -- Concatenation: 🎯 Lag trigger detected from:  .. game.Players.LocalPlayer.Name
    print("🎯 Lag trigger detected from: game.Players.LocalPlayer.Name")
end)