--[[This file was generated by Galactic Private Dumper v1.5]]
coroutine.wrap(function()
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
    coroutine.yield(...)
end)
--co_wrap_2(...)
coroutine.wrap(function() end)
--co_wrap_4(...)
local v6 = game:HttpGet("https://raw.githubusercontent.com/Footagesus/WindUI/main/dist/main.lua")
local v7 = loadstring(v6)()
local Players = game:GetService('Players')
local v9 = v7:CreateWindow({
    AccentColor = Color3.fromHex("#FFD700"),
    Icon = "solar:crown-bold",
    NewElements = true,
    OpenButton = {
        Color = ColorSequence.new(Color3.fromHex("#FFD700")),
        Enabled = true,
        Draggable = true,
        Title = "BENJO MENU"
    },
    Title = "THE BENJO PANEL ◆ PREMIUM",
    Folder = "benjo_final_instant"
})
local v10 = v9.Tab(v9, {
    Title = "Dashboard",
    Icon = "solar:home-bold"
})
-- Concatenation: User:  .. game.Players.LocalPlayer.Name
local v12 = v10:Button({
    Title = "User: game.Players.LocalPlayer.Name",
    Callback = function() end
})
local v13 = v10:Button({
    Title = "Rank: [ AUTHORIZED DEVELOPER ]",
    Callback = function() end
})
local v14 = v9.Tab(v9, {
    Title = "Main Games",
    Icon = "solar:star-bold"
})
local v15 = v14:Button({
    Title = "ADOPT ME PREMIUM",
    Callback = function()
        local v1 = game:HttpGet("https://pastefy.app/BaR5pLQ3/raw")
        local v2 = loadstring(v1)()
end,
    Icon = "solar:play-circle-bold",
    Description = "Unlock all exclusive premium features."
})
local v16 = v14:Button({
    Title = "Murder Mystery 2",
    Callback = function()
        local v1 = game:HttpGet("https://pastefy.app/FQ3Ctgd5/raw")
        local v2 = loadstring(v1)()
end,
    Icon = "solar:play-circle-bold",
    Description = "Silent Aim, ESP, and Auto-Farm."
})
local v17 = v14:Button({
    Title = "Brookhaven (Premium)",
    Callback = function()
        local v1 = game:HttpGet("https://api.luarmor.net/files/v3/loaders/fda9babd071d6b536a745774b6bc681c.lua")
        local v2 = loadstring(v1)()
end,
    Icon = "solar:play-circle-bold",
    Description = "Unlock all gamepasses & house features."
})
local v18 = v9.Tab(v9, {
    Title = "Other Games",
    Icon = "solar:gamepad-bold"
})
local v19 = v18:Button({
    Title = "Blox Fruits",
    Callback = function()
        local v1 = game:HttpGet("https://api.luarmor.net/files/v3/loaders/fda9babd071d6b536a745774b6bc681c.lua")
        local v2 = loadstring(v1)()
end,
    Description = "Premium Leveling & Farm."
})
local v20 = v18:Button({
    Title = "Arsenal",
    Callback = function()
        local v1 = game:HttpGet("https://raw.githubusercontent.com/0x0d3f/Quartyz/main/Gold.lua")
        local v2 = loadstring(v1)()
end,
    Description = "Aimbot, ESP, and Gun Mods."
})
local v21 = v18:Button({
    Title = "Rivals",
    Callback = function()
        local v1 = game:HttpGet("https://raw.githubusercontent.com/blexn9/Script/refs/heads/main/Main")
        local v2 = loadstring(v1)()
end,
    Description = "Silent Aim & ESP."
})
local v22 = v9.Tab(v9, {
    Title = "Settings",
    Icon = "solar:settings-bold"
})
local v23 = v22.Slider(v22, {
    Title = "WalkSpeed",
    Value = {
        Max = 250,
        Default = 16,
        Min = 16
    },
    Callback = function()
        game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = nil
end
})
local v24 = v22:Button({
    Title = "Server Hop",
    Callback = function()
        local v1 = game:HttpGet("https://raw.githubusercontent.com/K00LKids/ServerHop/main/Hop.lua")
        local v2 = loadstring(v1)()
end
})
local v25 = v9.Tab(v9, {
    Title = "Credits",
    Icon = "solar:info-circle-bold"
})
local v26 = v25:Button({
    Title = "Owner: BENJO",
    Callback = function()
        setclipboard("https://discord.gg/Uwwbd2T3cf")
        local v2 = v7:Notify({
    Title = "Copied",
    Duration = 3,
    Content = "Discord link copied to clipboard!"
})
end,
    Description = "Click to copy Discord link."
})
local v27 = v25:Button({
    Title = "Join Discord",
    Callback = function()
        setclipboard("https://discord.gg/Uwwbd2T3cf")
end,
    Description = "https://discord.gg/Uwwbd2T3cf"
})
local v28 = v9.SelectTab(v9, v14)
local v29 = v7:Notify({
    Title = "BENJO PANEL",
    Duration = 5,
    Content = "Credits updated with new Discord!"
})